var continents = {
  "AF": [
    "Algeria", 
    "Angola", 
    "Benin", 
    "Botswana", 
    "Burkina Faso", 
    "Burundi", 
    "Cameroon", 
    "Cape Verde", 
    "Central African Republic", 
    "Chad", 
    "Comoros", 
    "Democratic Republic of the Congo", 
    "Congo", 
    "C\u00f4te d'Ivoire", 
    "Djibouti", 
    "Egypt", 
    "Equatorial Guinea", 
    "Eritrea", 
    "Ethiopia", 
    "Gabon", 
    "Gambia", 
    "Ghana", 
    "Guinea", 
    "Guinea-Bissau", 
    "Kenya", 
    "Lesotho", 
    "Liberia", 
    "Libyan Arab Jamahiriya", 
    "Madagascar", 
    "Malawi", 
    "Mali", 
    "Mauritania", 
    "Mauritius", 
    "Mayotte", 
    "Morocco", 
    "Mozambique", 
    "Namibia", 
    "Niger", 
    "Nigeria", 
    "Reunion", 
    "Rwanda", 
    "Saint Helena", 
    "Sao Tome and Principe", 
    "Senegal", 
    "Seychelles", 
    "Sierra Leone", 
    "Somalia", 
    "South Africa", 
    "Sudan", 
    "Swaziland", 
    "United Republic of Tanzania", 
    "Togo", 
    "Tunisia", 
    "Uganda", 
    "Western Sahara", 
    "Zambia", 
    "Zimbabwe"
  ], 
  "NA": [
    "Anguilla", 
    "Antigua and Barbuda", 
    "Aruba", 
    "Bahamas", 
    "Barbados", 
    "Belize", 
    "Bermuda", 
    "British Virgin Islands", 
    "Canada", 
    "Cayman Islands", 
    "Costa Rica", 
    "Cuba", 
    "Dominica", 
    "Dominican Republic", 
    "El Salvador", 
    "Greenland", 
    "Grenada", 
    "Guadeloupe", 
    "Guatemala", 
    "Haiti", 
    "Honduras", 
    "Jamaica", 
    "Martinique", 
    "Mexico", 
    "Montserrat", 
    "Netherlands Antilles", 
    "Nicaragua", 
    "Panama", 
    "Puerto Rico", 
    "Saint Barthelemy", 
    "Saint Kitts and Nevis", 
    "Saint Lucia", 
    "Saint Martin", 
    "Saint Pierre and Miquelon", 
    "Saint Vincent and the Grenadines", 
    "Trinidad and Tobago", 
    "Turks and Caicos Islands", 
    "United States of America", 
    "United States Virgin Islands"
  ], 
  "OC": [
    "American Samoa", 
    "Australia", 
    "Cook Islands", 
    "Fiji", 
    "French Polynesia", 
    "Guam", 
    "Kiribati", 
    "Marshall Islands", 
    "Micronesia (Federated States of)", 
    "Nauru", 
    "New Caledonia", 
    "New Zealand", 
    "Niue", 
    "Norfolk Island", 
    "Northern Mariana Islands", 
    "Palau", 
    "Papua New Guinea", 
    "Pitcairn Islands", 
    "Samoa", 
    "Solomon Islands", 
    "Tokelau", 
    "Tonga", 
    "Tuvalu", 
    "United States Minor Outlying Islands", 
    "Vanuatu", 
    "Wallis and Futuna Islands"
  ], 
  "AN": [
    "Antarctica (the territory South of 60 deg S)", 
    "Bouvet Island (Bouvetoya)", 
    "French Southern Territories", 
    "Heard Island and McDonald Islands", 
    "South Georgia and the South Sandwich Islands"
  ], 
  "AS": [
    "Afghanistan", 
    "Armenia", 
    "Azerbaijan", 
    "Bahrain", 
    "Bangladesh", 
    "Bhutan", 
    "British Indian Ocean Territory (Chagos Archipelago)", 
    "Brunei Darussalam", 
    "Cambodia", 
    "China", 
    "Christmas Island", 
    "Cocos (Keeling) Islands", 
    "Cyprus", 
    "Georgia", 
    "Hong Kong", 
    "India", 
    "Indonesia", 
    "Iran (Islamic Republic of)", 
    "Iraq", 
    "Israel", 
    "Japan", 
    "Jordan", 
    "Kazakhstan", 
    "Democratic People's Republic of Korea", 
    "Republic of Korea", 
    "Kuwait", 
    "Kyrgyzstan", 
    "Lao People's Democratic Republic", 
    "Lebanon", 
    "Macao", 
    "Malaysia", 
    "Maldives", 
    "Mongolia", 
    "Myanmar", 
    "Nepal", 
    "Oman", 
    "Pakistan", 
    "Occupied Palestinian Territory", 
    "Philippines", 
    "Qatar", 
    "Saudi Arabia", 
    "Singapore", 
    "Sri Lanka", 
    "Syrian Arab Republic", 
    "Taiwan", 
    "Tajikistan", 
    "Thailand", 
    "Timor-Leste", 
    "Turkey", 
    "Turkmenistan", 
    "United Arab Emirates", 
    "Uzbekistan", 
    "Viet Nam", 
    "Yemen"
  ], 
  "EU": [
    "\u00c5land Islands", 
    "Albania", 
    "Andorra", 
    "Austria", 
    "Belarus", 
    "Belgium", 
    "Bosnia and Herzegovina", 
    "Bulgaria", 
    "Croatia", 
    "Czech Republic", 
    "Denmark", 
    "Estonia", 
    "Faroe Islands", 
    "Finland", 
    "France", 
    "Germany", 
    "Gibraltar", 
    "Greece", 
    "Guernsey", 
    "Holy See (Vatican City State)", 
    "Hungary", 
    "Iceland", 
    "Ireland", 
    "Isle of Man", 
    "Italy", 
    "Jersey", 
    "Latvia", 
    "Liechtenstein", 
    "Lithuania", 
    "Luxembourg", 
    "TFYR Macedonia", 
    "Malta", 
    "Republic of Moldova", 
    "Monaco", 
    "Montenegro", 
    "Netherlands", 
    "Norway", 
    "Poland", 
    "Portugal", 
    "Romania", 
    "Russian Federation", 
    "San Marino", 
    "Serbia", 
    "Slovakia", 
    "Slovenia", 
    "Spain", 
    "Svalbard & Jan Mayen Islands", 
    "Sweden", 
    "Switzerland", 
    "Ukraine", 
    "United Kingdom"
  ], 
  "SA": [
    "Argentina", 
    "Bolivia", 
    "Brazil", 
    "Chile", 
    "Colombia", 
    "Ecuador", 
    "Falkland Islands (Malvinas)", 
    "French Guiana", 
    "Guyana", 
    "Paraguay", 
    "Peru", 
    "Suriname", 
    "Uruguay", 
    "Venezuela"
  ]
}
